# Day 06
## Affine Transformation (Cont'd)

- Goal:
    1. Preprocess the image according to the instructions.
    2. Preprocess the image by constructing a transformation matrix with three pair of points.

### (a)

In [1]:
import cv2
import numpy as np

img = cv2.imread('Lenna_(test_image).png', cv2.IMREAD_COLOR)

In [2]:
rows, cols = img.shape[:2]

# rotate 45 degrees counter-clockwise && scale the image by a factor of 0.5
M_linear = cv2.getRotationMatrix2D((cols//2, rows//2), 45, 0.5)
print("linear map\n", M_linear)
dst_linear = cv2.warpAffine(img, M_linear, (cols, rows))

# translate the image by (100, -50)
M_translate = np.array([[1, 0, 100],
                        [0, 1, -50]], dtype = np.float32)
print("translation\n", M_translate)
dst = cv2.warpAffine(dst_linear, M_translate, (cols, rows))

img_preprocessed = np.hstack((img, dst_linear, dst))
cv2.imshow('affine transformation', img_preprocessed)
cv2.waitKey(0)
cv2.destroyAllWindows()

linear map
 [[  0.35355339   0.35355339  74.98066402]
 [ -0.35355339   0.35355339 256.        ]]
translation
 [[  1.   0. 100.]
 [  0.   1. -50.]]


### (b)

In [3]:
pts1 = np.array([[50,50], [300,100], [200,300]], dtype = np.float32)
pts2 = np.array([[80,80], [330,150], [300,300]], dtype = np.float32)

M = cv2.getAffineTransform(pts1, pts2)
dst = cv2.warpAffine(img, M, (cols,rows))

# mark the points
img_copy = img.copy()
for idx, pts in enumerate(pts1):
    pts = tuple(map(int, pts))
    cv2.circle(img_copy, pts, 3, (0, 255, 0), -1)
    cv2.putText(img_copy, str(idx), (pts[0] + 5, pts[1] + 5), 0, 1, (0, 255, 0), 2)

for idx, pts in enumerate(pts2):
    pts = tuple(map(int, pts))
    cv2.circle(dst, pts, 3, (0, 255, 0), -1)
    cv2.putText(dst, str(idx), (pts[0] + 5, pts[1] + 5), 0, 1, (0, 255, 0), 2)

img_preprocessed = np.hstack((img_copy, dst))
cv2.imshow('affine transformation', img_preprocessed)
cv2.waitKey(0)
cv2.destroyAllWindows()